{
 "title": "Oxygenium Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>General</span>\n</div>"
   }
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{app=\"oxygenium\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"oxygenium\"}"
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "stat",
   "description": "Number of connected peers",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oxygenium_peers_total{app=\"oxygenium\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{app=\"oxygenium\"}, \"jdk\", \", \", \"vendor\", \"version\")"
    }
   ]
  },
  {
   "title": "Number of Discovered Brokers",
   "type": "stat",
   "description": "Number of discovered brokers",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oxygenium_discovered_broker_size{app=\"oxygenium\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"oxygenium\"}*1000"
    }
   ]
  },
  {
   "title": "Oxygenium Version",
   "type": "stat",
   "description": "Oxygenium Version",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oxygenium_build_info{app=\"oxygenium\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Mempool</span>\n</div>"
   }
  },
  {
   "title": "Transaction Count Per Group (Shared Pool)",
   "type": "graph",
   "description": "Number of transactions in shared pool per group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (group_index, chain_index)(oxygenium_mempool_shared_pool_transactions_total{app=\"oxygenium\"})",
     "legendFormat": "group {{group_index}}, chain {{chain_index}}"
    }
   ]
  },
  {
   "title": "Total Transaction Count (Shared Pool)",
   "type": "graph",
   "description": "Total number of transactions in shared pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (oxygenium_mempool_shared_pool_transactions_total{app=\"oxygenium\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Transaction Count Per Group (Pending Pool)",
   "type": "graph",
   "description": "Number of transactions in pending pool per group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (group_index)(oxygenium_mempool_pending_pool_transactions_total{app=\"oxygenium\"})",
     "legendFormat": "Group index: {{group_index}}"
    }
   ]
  },
  {
   "title": "Total Transaction Count (Pending Pool)",
   "type": "graph",
   "description": "Total number of transactions in pending pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(oxygenium_mempool_pending_pool_transactions_total{app=\"oxygenium\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Network</span>\n</div>"
   }
  },
  {
   "title": "Download Speed Per Peer",
   "type": "graph",
   "description": "Download Speed (byte/second) per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_download_bytes_total{app=\"oxygenium\"}[2m])) by (remote_address) != 0",
     "legendFormat": "remote_address: {{remote_address}}"
    }
   ]
  },
  {
   "title": "Download Speed Total",
   "type": "graph",
   "description": "Total download Speed (byte/second)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_download_bytes_total{app=\"oxygenium\"}[2m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Upload Speed Per Peer",
   "type": "graph",
   "description": "Upload Speed (byte/second) per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_upload_bytes_total{app=\"oxygenium\"}[1m])) by (remote_address) != 0",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "Upload Speed Total",
   "type": "graph",
   "description": "Total upload Speed (byte/second)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_upload_bytes_total{app=\"oxygenium\"}[1m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Chain Validation</span>\n</div>"
   }
  },
  {
   "title": "Number of Payload Per Second (Per Payload)",
   "type": "graph",
   "description": "Number of payload per second, group by payload",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_payload_total{app=\"oxygenium\"}[1m])) by (payload_type)",
     "legendFormat": "{{payload_type}}"
    }
   ]
  },
  {
   "title": "Total Number of Payload Per Second",
   "type": "graph",
   "description": "Total number of payload per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_payload_total{app=\"oxygenium\"}[1m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Total Chain Validations Per Second",
   "type": "graph",
   "description": "Chain validation per second (Block and BlockHeader)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_chain_validation_total{app=\"oxygenium\"}[1m])) by (validation_type)",
     "legendFormat": "{{validation_type}}"
    }
   ]
  },
  {
   "title": "Chain Validation Time",
   "type": "graph",
   "description": "Validation time, both block validation and header validation. \n\n50 percentile, 90 percentil and 99 percentile",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(oxygenium_chain_validation_duration_milliseconds_bucket{app=\"oxygenium\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(oxygenium_chain_validation_duration_milliseconds_bucket{app=\"oxygenium\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(oxygenium_chain_validation_duration_milliseconds_bucket{app=\"oxygenium\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Failed Validations Per Second",
   "type": "graph",
   "description": "Failed chain validation per second (Block and BlockHeader)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_chain_validation_failed{app=\"oxygenium\"}[1m])) by (validation_type, invalid_status)",
     "legendFormat": "{{validation_type}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Blocks and Transactions</span>\n</div>"
   }
  },
  {
   "title": "Current Block Height Per Chain",
   "type": "bargauge",
   "description": "Current Block Height Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(oxygenium_block_current_height) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "description": "Current Block Height",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(oxygenium_block_current_height)",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Total Blocks Per Chain",
   "type": "bargauge",
   "description": "Total Blocks Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(oxygenium_blocks_total{app=\"oxygenium\"}) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Blocks",
   "type": "stat",
   "description": "Total Blocks Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(oxygenium_blocks_total{app=\"oxygenium\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Blocks Per Second Per Chain",
   "type": "graph",
   "description": "Blocks Per Second Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_blocks_received_total{app=\"oxygenium\"}[1m])) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Blocks Per Second",
   "type": "graph",
   "description": "Total Blocks Per Second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_blocks_received_total{app=\"oxygenium\"}[1m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Transaction Per Second Per Chain",
   "type": "graph",
   "description": "Transaction Per Second Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_transactions_received_total{app=\"oxygenium\"}[1m])) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Transaction Per Second",
   "type": "graph",
   "description": "Total ransaction Per Second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_transactions_received_total{app=\"oxygenium\"}[1m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Block Time ",
   "type": "graph",
   "description": "Block Time with Percentil",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(oxygenium_block_duration_milliseconds_bucket[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(oxygenium_block_duration_milliseconds_bucket[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(oxygenium_block_duration_milliseconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(oxygenium_block_duration_milliseconds_sum[30m])) / sum(rate(oxygenium_block_duration_milliseconds_count[30m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Total Headers Per Chain",
   "type": "bargauge",
   "description": "Total Headers Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "oxygenium_headers_total{app=\"oxygenium\"}",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Headers",
   "type": "stat",
   "description": "Total Headers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(oxygenium_headers_total{app=\"oxygenium\"})",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Headers Per Second Per Chain",
   "type": "graph",
   "description": "Headers Per Second Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_headers_received_total{app=\"oxygenium\"}[1m])) by (chain_from, chain_to)",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  },
  {
   "title": "Total Headers Per Second",
   "type": "graph",
   "description": "Total Headers Per Second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(oxygenium_headers_received_total{app=\"oxygenium\"}[1m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Estimated Network HashRate",
   "type": "graph",
   "description": "Average hashrate over all chains over 10 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(oxygenium_target_hash_rate_hertz[10m])) / sum(count_over_time(oxygenium_target_hash_rate_hertz[10m]))",
     "legendFormat": "HashRate"
    }
   ]
  },
  {
   "title": "Target Hash Rate Per Chain",
   "type": "graph",
   "description": "Target Hash Rate Per Chain",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "oxygenium_target_hash_rate_hertz{app=\"oxygenium\"}",
     "legendFormat": "Chain ({{chain_from}}, {{chain_to}})"
    }
   ]
  }
 ]
}