version: "3.3"

services:
  oxygenium_gpu_miner:
    image: oxygenium/gpu-miner:latest
    depends_on:
      - oxygenium
    restart: unless-stopped
    runtime: nvidia
    privileged: true
    command:
      - -a
      - oxygenium
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
