version: "3.3"

volumes:
  postgres-data: {}

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=explorer
    restart: unless-stopped

  explorer-backend:
    image: oxygenium/explorer-backend:1.2.0
    ports:
      - 9090:9090
    environment:
      - DB_HOST=postgres
      - BLOCKFLOW_HOST=oxygenium
      - EXPLORER_HOST=0.0.0.0
    depends_on:
      - postgres
      - oxygenium
    restart: unless-stopped

  explorer:
    image: oxygenium/explorer:latest
    ports:
      - 3001:3000
    depends_on:
      - explorer-backend
    restart: unless-stopped
