name: Styling

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck it:scalafmtCheck scalastyle test:scalastyle it:scalastyle doc
      - run: make assembly
      - run: sbt app/docker
      - run: sbt "tools/runMain org.alephium.tools.BuiltInFunctions" && test -z "$(git status --porcelain)"
